/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitest;

import guitest.customer.Address;
import guitest.customer.Contacts;
import guitest.customer.MaritalStatus;
import guitest.customer.PersonalDetails;
import java.awt.Color;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author HILTON9
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrame
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        suppliersDashboardLink = new javax.swing.JLabel();
        inventoryDashboardLink = new javax.swing.JLabel();
        cemeteryManagementDashboardLink = new javax.swing.JLabel();
        userManagementDashboardLink = new javax.swing.JLabel();
        eventCalenderDashboardLink = new javax.swing.JLabel();
        funeralPackagesDashboardLink = new javax.swing.JLabel();
        customersDashboardLink = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nintyDaysOverduePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sixtyDaysOverduePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        thirtyDaysOverduePanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        paidLastThirtyDaysPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        managePlansShortcut = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        managePlansShortcutText = new javax.swing.JLabel();
        createQuotationShortcut = new javax.swing.JPanel();
        createQuotationShortcutText2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        createQuotationShortcutText1 = new javax.swing.JLabel();
        capturePaymentDataShortcut = new javax.swing.JPanel();
        capturePaymentDataShortcutText2 = new javax.swing.JLabel();
        capturePaymentDataShortcutText1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        manageNotificationsShortcut = new javax.swing.JPanel();
        manageNotificationsShortcutText2 = new javax.swing.JLabel();
        manageNotificationsShortcutText1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        reportsShortcut = new javax.swing.JPanel();
        reportsShortcutText = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Joe Admin Systems");

        jPanel1.setBackground(new java.awt.Color(10, 18, 50));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        suppliersDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        suppliersDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        suppliersDashboardLink.setText("Suppliers");
        suppliersDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppliersDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppliersDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliersDashboardLinkMouseExited(evt);
            }
        });

        inventoryDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        inventoryDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        inventoryDashboardLink.setText("Inventory");
        inventoryDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventoryDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryDashboardLinkMouseExited(evt);
            }
        });

        cemeteryManagementDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        cemeteryManagementDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        cemeteryManagementDashboardLink.setText("Cemetery Management");
        cemeteryManagementDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cemeteryManagementDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cemeteryManagementDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cemeteryManagementDashboardLinkMouseExited(evt);
            }
        });

        userManagementDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        userManagementDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        userManagementDashboardLink.setText("User Management");
        userManagementDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userManagementDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userManagementDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userManagementDashboardLinkMouseExited(evt);
            }
        });

        eventCalenderDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        eventCalenderDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        eventCalenderDashboardLink.setText("Event Calender");
        eventCalenderDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eventCalenderDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventCalenderDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventCalenderDashboardLinkMouseExited(evt);
            }
        });

        funeralPackagesDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        funeralPackagesDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        funeralPackagesDashboardLink.setText("Funeral Packages");
        funeralPackagesDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        funeralPackagesDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funeralPackagesDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funeralPackagesDashboardLinkMouseExited(evt);
            }
        });

        customersDashboardLink.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        customersDashboardLink.setForeground(new java.awt.Color(255, 255, 255));
        customersDashboardLink.setText("Sales");
        customersDashboardLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customersDashboardLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersDashboardLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customersDashboardLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customersDashboardLinkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customersDashboardLink)
                    .addComponent(funeralPackagesDashboardLink)
                    .addComponent(eventCalenderDashboardLink)
                    .addComponent(userManagementDashboardLink)
                    .addComponent(cemeteryManagementDashboardLink)
                    .addComponent(inventoryDashboardLink)
                    .addComponent(suppliersDashboardLink))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(customersDashboardLink)
                .addGap(18, 18, 18)
                .addComponent(suppliersDashboardLink)
                .addGap(18, 18, 18)
                .addComponent(inventoryDashboardLink)
                .addGap(18, 18, 18)
                .addComponent(cemeteryManagementDashboardLink)
                .addGap(18, 18, 18)
                .addComponent(userManagementDashboardLink)
                .addGap(18, 18, 18)
                .addComponent(eventCalenderDashboardLink)
                .addGap(18, 18, 18)
                .addComponent(funeralPackagesDashboardLink)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Keeping you updated.");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 410, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel2.setText("Joe Admin Systems");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 460, 60));

        jPanel7.setBackground(new java.awt.Color(32, 50, 81));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nintyDaysOverduePanel.setBackground(new java.awt.Color(33, 169, 242));
        nintyDaysOverduePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nintyDaysOverduePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nintyDaysOverduePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nintyDaysOverduePanelMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("R5175.00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("216");

        javax.swing.GroupLayout nintyDaysOverduePanelLayout = new javax.swing.GroupLayout(nintyDaysOverduePanel);
        nintyDaysOverduePanel.setLayout(nintyDaysOverduePanelLayout);
        nintyDaysOverduePanelLayout.setHorizontalGroup(
            nintyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nintyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nintyDaysOverduePanelLayout.setVerticalGroup(
            nintyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nintyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nintyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(47, 47, 47))
        );

        jPanel7.add(nintyDaysOverduePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, 50));

        sixtyDaysOverduePanel.setBackground(new java.awt.Color(0, 117, 194));
        sixtyDaysOverduePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sixtyDaysOverduePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sixtyDaysOverduePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sixtyDaysOverduePanelMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("R5175.00");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("156");

        javax.swing.GroupLayout sixtyDaysOverduePanelLayout = new javax.swing.GroupLayout(sixtyDaysOverduePanel);
        sixtyDaysOverduePanel.setLayout(sixtyDaysOverduePanelLayout);
        sixtyDaysOverduePanelLayout.setHorizontalGroup(
            sixtyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sixtyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sixtyDaysOverduePanelLayout.setVerticalGroup(
            sixtyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sixtyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sixtyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(sixtyDaysOverduePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 270, 50));

        thirtyDaysOverduePanel.setBackground(new java.awt.Color(250, 125, 0));
        thirtyDaysOverduePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thirtyDaysOverduePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thirtyDaysOverduePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thirtyDaysOverduePanelMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("R5175.00");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("176");

        javax.swing.GroupLayout thirtyDaysOverduePanelLayout = new javax.swing.GroupLayout(thirtyDaysOverduePanel);
        thirtyDaysOverduePanel.setLayout(thirtyDaysOverduePanelLayout);
        thirtyDaysOverduePanelLayout.setHorizontalGroup(
            thirtyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirtyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        thirtyDaysOverduePanelLayout.setVerticalGroup(
            thirtyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirtyDaysOverduePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thirtyDaysOverduePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(thirtyDaysOverduePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 300, 50));

        paidLastThirtyDaysPanel.setBackground(new java.awt.Color(125, 205, 0));
        paidLastThirtyDaysPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paidLastThirtyDaysPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paidLastThirtyDaysPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paidLastThirtyDaysPanelMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("R5175.00");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("875");

        javax.swing.GroupLayout paidLastThirtyDaysPanelLayout = new javax.swing.GroupLayout(paidLastThirtyDaysPanel);
        paidLastThirtyDaysPanel.setLayout(paidLastThirtyDaysPanelLayout);
        paidLastThirtyDaysPanelLayout.setHorizontalGroup(
            paidLastThirtyDaysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paidLastThirtyDaysPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paidLastThirtyDaysPanelLayout.setVerticalGroup(
            paidLastThirtyDaysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paidLastThirtyDaysPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paidLastThirtyDaysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(paidLastThirtyDaysPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 370, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Paid in the Last 30 Days");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 210, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("90 days Overdue");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("60 Days Overdue");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 210, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("30 Days Overdue");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 210, 30));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1170, -1));

        managePlansShortcut.setBackground(new java.awt.Color(32, 50, 81));
        managePlansShortcut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        managePlansShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePlansShortcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managePlansShortcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managePlansShortcutMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-product-management-96.png")); // NOI18N

        managePlansShortcutText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        managePlansShortcutText.setForeground(new java.awt.Color(255, 255, 255));
        managePlansShortcutText.setText("Manage Plans");

        javax.swing.GroupLayout managePlansShortcutLayout = new javax.swing.GroupLayout(managePlansShortcut);
        managePlansShortcut.setLayout(managePlansShortcutLayout);
        managePlansShortcutLayout.setHorizontalGroup(
            managePlansShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePlansShortcutLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managePlansShortcutLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(managePlansShortcutText)
                .addGap(36, 36, 36))
        );
        managePlansShortcutLayout.setVerticalGroup(
            managePlansShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePlansShortcutLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel15)
                .addGap(40, 40, 40)
                .addComponent(managePlansShortcutText)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel7.add(managePlansShortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 270));

        createQuotationShortcut.setBackground(new java.awt.Color(32, 50, 81));
        createQuotationShortcut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        createQuotationShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createQuotationShortcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createQuotationShortcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createQuotationShortcutMouseExited(evt);
            }
        });

        createQuotationShortcutText2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        createQuotationShortcutText2.setForeground(new java.awt.Color(255, 255, 255));
        createQuotationShortcutText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createQuotationShortcutText2.setText("Quotation");

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-add-receipt-96.png")); // NOI18N

        createQuotationShortcutText1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        createQuotationShortcutText1.setForeground(new java.awt.Color(255, 255, 255));
        createQuotationShortcutText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createQuotationShortcutText1.setText("Create");

        javax.swing.GroupLayout createQuotationShortcutLayout = new javax.swing.GroupLayout(createQuotationShortcut);
        createQuotationShortcut.setLayout(createQuotationShortcutLayout);
        createQuotationShortcutLayout.setHorizontalGroup(
            createQuotationShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createQuotationShortcutLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(createQuotationShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(createQuotationShortcutText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createQuotationShortcutText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(52, 52, 52))
        );
        createQuotationShortcutLayout.setVerticalGroup(
            createQuotationShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createQuotationShortcutLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(26, 26, 26)
                .addComponent(createQuotationShortcutText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createQuotationShortcutText2)
                .addGap(19, 19, 19))
        );

        jPanel7.add(createQuotationShortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 210, 270));

        capturePaymentDataShortcut.setBackground(new java.awt.Color(32, 50, 81));
        capturePaymentDataShortcut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        capturePaymentDataShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        capturePaymentDataShortcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                capturePaymentDataShortcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                capturePaymentDataShortcutMouseExited(evt);
            }
        });

        capturePaymentDataShortcutText2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        capturePaymentDataShortcutText2.setForeground(new java.awt.Color(255, 255, 255));
        capturePaymentDataShortcutText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capturePaymentDataShortcutText2.setText("Payment Data");

        capturePaymentDataShortcutText1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        capturePaymentDataShortcutText1.setForeground(new java.awt.Color(255, 255, 255));
        capturePaymentDataShortcutText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capturePaymentDataShortcutText1.setText("Capture");

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-card-payment-96.png")); // NOI18N

        javax.swing.GroupLayout capturePaymentDataShortcutLayout = new javax.swing.GroupLayout(capturePaymentDataShortcut);
        capturePaymentDataShortcut.setLayout(capturePaymentDataShortcutLayout);
        capturePaymentDataShortcutLayout.setHorizontalGroup(
            capturePaymentDataShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capturePaymentDataShortcutLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(capturePaymentDataShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capturePaymentDataShortcutText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capturePaymentDataShortcutText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capturePaymentDataShortcutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(55, 55, 55))
        );
        capturePaymentDataShortcutLayout.setVerticalGroup(
            capturePaymentDataShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capturePaymentDataShortcutLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(9, 9, 9)
                .addComponent(capturePaymentDataShortcutText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capturePaymentDataShortcutText2)
                .addGap(20, 20, 20))
        );

        jPanel7.add(capturePaymentDataShortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 210, 270));

        manageNotificationsShortcut.setBackground(new java.awt.Color(32, 50, 81));
        manageNotificationsShortcut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        manageNotificationsShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageNotificationsShortcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageNotificationsShortcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageNotificationsShortcutMouseExited(evt);
            }
        });

        manageNotificationsShortcutText2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        manageNotificationsShortcutText2.setForeground(new java.awt.Color(255, 255, 255));
        manageNotificationsShortcutText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageNotificationsShortcutText2.setText("Notifications");

        manageNotificationsShortcutText1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        manageNotificationsShortcutText1.setForeground(new java.awt.Color(255, 255, 255));
        manageNotificationsShortcutText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageNotificationsShortcutText1.setText("Manage");

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-sms-96.png")); // NOI18N

        javax.swing.GroupLayout manageNotificationsShortcutLayout = new javax.swing.GroupLayout(manageNotificationsShortcut);
        manageNotificationsShortcut.setLayout(manageNotificationsShortcutLayout);
        manageNotificationsShortcutLayout.setHorizontalGroup(
            manageNotificationsShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageNotificationsShortcutLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageNotificationsShortcutLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(manageNotificationsShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manageNotificationsShortcutText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageNotificationsShortcutText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        manageNotificationsShortcutLayout.setVerticalGroup(
            manageNotificationsShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageNotificationsShortcutLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(25, 25, 25)
                .addComponent(manageNotificationsShortcutText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageNotificationsShortcutText2)
                .addGap(19, 19, 19))
        );

        jPanel7.add(manageNotificationsShortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 210, 270));

        reportsShortcut.setBackground(new java.awt.Color(32, 50, 81));
        reportsShortcut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        reportsShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportsShortcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsShortcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsShortcutMouseExited(evt);
            }
        });

        reportsShortcutText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        reportsShortcutText.setForeground(new java.awt.Color(255, 255, 255));
        reportsShortcutText.setText("Reports");

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-statistic-document-96.png")); // NOI18N

        javax.swing.GroupLayout reportsShortcutLayout = new javax.swing.GroupLayout(reportsShortcut);
        reportsShortcut.setLayout(reportsShortcutLayout);
        reportsShortcutLayout.setHorizontalGroup(
            reportsShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsShortcutLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(reportsShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportsShortcutLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportsShortcutLayout.createSequentialGroup()
                        .addComponent(reportsShortcutText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        reportsShortcutLayout.setVerticalGroup(
            reportsShortcutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportsShortcutLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(27, 27, 27)
                .addComponent(reportsShortcutText)
                .addGap(43, 43, 43))
        );

        jPanel7.add(reportsShortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 210, 270));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 1170, -1));
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        jButton1.setBackground(new java.awt.Color(33, 169, 242));
        jButton1.setForeground(new java.awt.Color(33, 169, 242));
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, 50));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Deshboard");

        jTextField2.setBorder(null);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-search-32.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hilton9\\Documents\\NetBeansProjects\\icons\\icons8-male-user-64.png")); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 658, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jLabel9)
                .addGap(25, 25, 25))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nintyDaysOverduePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nintyDaysOverduePanelMouseEntered
        nintyDaysOverduePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_nintyDaysOverduePanelMouseEntered

    private void nintyDaysOverduePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nintyDaysOverduePanelMouseExited
        nintyDaysOverduePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    }//GEN-LAST:event_nintyDaysOverduePanelMouseExited

    private void sixtyDaysOverduePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixtyDaysOverduePanelMouseEntered
        sixtyDaysOverduePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    }//GEN-LAST:event_sixtyDaysOverduePanelMouseEntered

    private void sixtyDaysOverduePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixtyDaysOverduePanelMouseExited
        sixtyDaysOverduePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    }//GEN-LAST:event_sixtyDaysOverduePanelMouseExited

    private void thirtyDaysOverduePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirtyDaysOverduePanelMouseEntered
        thirtyDaysOverduePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    }//GEN-LAST:event_thirtyDaysOverduePanelMouseEntered

    private void thirtyDaysOverduePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirtyDaysOverduePanelMouseExited
        thirtyDaysOverduePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());

    }//GEN-LAST:event_thirtyDaysOverduePanelMouseExited

    private void paidLastThirtyDaysPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidLastThirtyDaysPanelMouseEntered
        paidLastThirtyDaysPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    }//GEN-LAST:event_paidLastThirtyDaysPanelMouseEntered

    private void paidLastThirtyDaysPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidLastThirtyDaysPanelMouseExited
        paidLastThirtyDaysPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_paidLastThirtyDaysPanelMouseExited

    private void suppliersDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersDashboardLinkMouseEntered
        String text = "<html><u>Suppliers</u></html>";
        suppliersDashboardLink.setText(text);
    }//GEN-LAST:event_suppliersDashboardLinkMouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
    }//GEN-LAST:event_jPanel1MouseExited

    private void suppliersDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersDashboardLinkMouseExited
        suppliersDashboardLink.setText("Suppliers");
    }//GEN-LAST:event_suppliersDashboardLinkMouseExited

    private void inventoryDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDashboardLinkMouseEntered
        String text = "<html><u>Inventory</u></html>";
        inventoryDashboardLink.setText(text);
    }//GEN-LAST:event_inventoryDashboardLinkMouseEntered

    private void inventoryDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDashboardLinkMouseExited
        inventoryDashboardLink.setText("Inventory");
    }//GEN-LAST:event_inventoryDashboardLinkMouseExited

    private void cemeteryManagementDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cemeteryManagementDashboardLinkMouseEntered
        String text = "<html><u>Cemetery Management</u></html>";
        cemeteryManagementDashboardLink.setText(text);
    }//GEN-LAST:event_cemeteryManagementDashboardLinkMouseEntered

    private void cemeteryManagementDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cemeteryManagementDashboardLinkMouseExited
        cemeteryManagementDashboardLink.setText("Cemetery Management");
    }//GEN-LAST:event_cemeteryManagementDashboardLinkMouseExited

    private void userManagementDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagementDashboardLinkMouseEntered
        String text = "<html><u>User Management</u></html>";
        userManagementDashboardLink.setText(text);
    }//GEN-LAST:event_userManagementDashboardLinkMouseEntered

    private void userManagementDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagementDashboardLinkMouseExited
        userManagementDashboardLink.setText("User Management");
    }//GEN-LAST:event_userManagementDashboardLinkMouseExited

    private void eventCalenderDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventCalenderDashboardLinkMouseEntered
        String text = "<html><u>Event Calender</u></html>";
        eventCalenderDashboardLink.setText(text);
    }//GEN-LAST:event_eventCalenderDashboardLinkMouseEntered

    private void eventCalenderDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventCalenderDashboardLinkMouseExited
        eventCalenderDashboardLink.setText("Event Calender");
    }//GEN-LAST:event_eventCalenderDashboardLinkMouseExited

    private void funeralPackagesDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funeralPackagesDashboardLinkMouseEntered
        String text = "<html><u>Funeral Packages</u></html>";
        funeralPackagesDashboardLink.setText(text);
    }//GEN-LAST:event_funeralPackagesDashboardLinkMouseEntered

    private void funeralPackagesDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funeralPackagesDashboardLinkMouseExited
        funeralPackagesDashboardLink.setText("Funeral Packages");
    }//GEN-LAST:event_funeralPackagesDashboardLinkMouseExited

    private void customersDashboardLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersDashboardLinkMouseEntered
        String text = "<html><u>Sales</u></html>";
        customersDashboardLink.setText(text);
    }//GEN-LAST:event_customersDashboardLinkMouseEntered

    private void customersDashboardLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersDashboardLinkMouseExited
        customersDashboardLink.setText("Sales");
    }//GEN-LAST:event_customersDashboardLinkMouseExited

    private void managePlansShortcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePlansShortcutMouseEntered
        String text = "<html><u>Manage Plans</u></html>";        
        managePlansShortcutText.setText(text);
    }//GEN-LAST:event_managePlansShortcutMouseEntered

    private void managePlansShortcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePlansShortcutMouseExited
        managePlansShortcutText.setText("Manage Plans");
    }//GEN-LAST:event_managePlansShortcutMouseExited

    private void createQuotationShortcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createQuotationShortcutMouseEntered
        String text1 = "<html><u>Create</u></html>";        
        String text2 = "<html><u>Quotation</u></html>";        
        createQuotationShortcutText1.setText(text1);
        createQuotationShortcutText2.setText(text2);
    }//GEN-LAST:event_createQuotationShortcutMouseEntered

    private void createQuotationShortcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createQuotationShortcutMouseExited
        createQuotationShortcutText1.setText("Create");
        createQuotationShortcutText2.setText("Quotation");

    }//GEN-LAST:event_createQuotationShortcutMouseExited

    private void capturePaymentDataShortcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capturePaymentDataShortcutMouseEntered
        String text1 = "<html><u>Capture</u></html>";        
        String text2 = "<html><u>Payment Data</u></html>";        
        capturePaymentDataShortcutText1.setText(text1);
        capturePaymentDataShortcutText2.setText(text2);
    }//GEN-LAST:event_capturePaymentDataShortcutMouseEntered

    private void capturePaymentDataShortcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capturePaymentDataShortcutMouseExited
        capturePaymentDataShortcutText1.setText("Capture");
        capturePaymentDataShortcutText2.setText("Payment Data");

    }//GEN-LAST:event_capturePaymentDataShortcutMouseExited

    private void manageNotificationsShortcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNotificationsShortcutMouseEntered
        String text1 = "<html><u>Manage</u></html>";        
        String text2 = "<html><u>Notifications</u></html>";        
        manageNotificationsShortcutText1.setText(text1);
        manageNotificationsShortcutText2.setText(text2);
    }//GEN-LAST:event_manageNotificationsShortcutMouseEntered

    private void manageNotificationsShortcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNotificationsShortcutMouseExited
        manageNotificationsShortcutText1.setText("Manage");
        manageNotificationsShortcutText2.setText("Notifications");

    }//GEN-LAST:event_manageNotificationsShortcutMouseExited

    private void reportsShortcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsShortcutMouseEntered
        String text = "<html><u>Reports</u></html>";        
        reportsShortcutText.setText(text);

    }//GEN-LAST:event_reportsShortcutMouseEntered

    private void reportsShortcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsShortcutMouseExited
        reportsShortcutText.setText("Reports");
    }//GEN-LAST:event_reportsShortcutMouseExited

    private void customersDashboardLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersDashboardLinkMouseClicked
        new CustomerInformation().setVisible(true);
    }//GEN-LAST:event_customersDashboardLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    javax.swing.UIManager.setLookAndFeel( javax.swing.UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel capturePaymentDataShortcut;
    private javax.swing.JLabel capturePaymentDataShortcutText1;
    private javax.swing.JLabel capturePaymentDataShortcutText2;
    private javax.swing.JLabel cemeteryManagementDashboardLink;
    private javax.swing.JPanel createQuotationShortcut;
    private javax.swing.JLabel createQuotationShortcutText1;
    private javax.swing.JLabel createQuotationShortcutText2;
    private javax.swing.JLabel customersDashboardLink;
    private javax.swing.JLabel eventCalenderDashboardLink;
    private javax.swing.JLabel funeralPackagesDashboardLink;
    private javax.swing.JLabel inventoryDashboardLink;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel manageNotificationsShortcut;
    private javax.swing.JLabel manageNotificationsShortcutText1;
    private javax.swing.JLabel manageNotificationsShortcutText2;
    private javax.swing.JPanel managePlansShortcut;
    private javax.swing.JLabel managePlansShortcutText;
    private javax.swing.JPanel nintyDaysOverduePanel;
    private javax.swing.JPanel paidLastThirtyDaysPanel;
    private javax.swing.JPanel reportsShortcut;
    private javax.swing.JLabel reportsShortcutText;
    private javax.swing.JPanel sixtyDaysOverduePanel;
    private javax.swing.JLabel suppliersDashboardLink;
    private javax.swing.JPanel thirtyDaysOverduePanel;
    private javax.swing.JLabel userManagementDashboardLink;
    // End of variables declaration//GEN-END:variables
}
